CREATE TABLE IF NOT EXISTS pedidos (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 produto_id INT NULL,
 produto_nome VARCHAR(150) NOT NULL,
 valor DECIMAL(10,2) NOT NULL,
 nome VARCHAR(150) NOT NULL,
 email VARCHAR(180) NOT NULL,
 telefone VARCHAR(40) NOT NULL,
 cpf VARCHAR(20) NULL,
 cep VARCHAR(15) NOT NULL,
 endereco VARCHAR(220) NOT NULL,
 numero VARCHAR(30) NOT NULL,
 complemento VARCHAR(120) NULL,
 cidade VARCHAR(100) NOT NULL,
 estado CHAR(2) NOT NULL,
 status VARCHAR(40) NOT NULL DEFAULT 'aguardando_pagamento',
 pagbank_checkout_id VARCHAR(80) NULL,
 payment_status VARCHAR(40) NULL,
 criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (id),
 INDEX idx_email (email),
 INDEX idx_status (status),
 INDEX idx_pagbank_checkout (pagbank_checkout_id),
 INDEX idx_criado_em (criado_em)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
